name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always


permissions:
  contents: write

jobs:
  publish-bin-to-github:
    name: Publish bin tool to Github
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-musl
          cross: false
          bin_suffix: x86_64-linux
        - build: arm-v7
          os: ubuntu-latest
          rust: stable
          target: armv7-unknown-linux-gnueabihf
          linker: gcc-arm-linux-gnueabihf
          cross: true
          bin_suffix: arm-v7-linux
        - build: aarch64
          os: ubuntu-latest
          rust: stable
          target: aarch64-unknown-linux-gnu
          linker: gcc-aarch64-linux-gnu
          cross: true
          bin_suffix: aarch64-linux
        - build: macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
          cross: false
          bin_suffix: macos
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1

    - name: Cache
      uses: actions/cache@v4.1.2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: ${{ runner.os }}-${{ matrix.rust }}

    - name: Install Linker
      if: matrix.cross
      run: |
        sudo apt update
        sudo apt install ${{ matrix.linker }}
        cat .cargo/config.github >> .cargo/config
    - name: Install Rust
      run: |
        rustup install ${{ matrix.rust }}
        rustup target add ${{ matrix.target }}
        rustup show
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    - name: Copy and rename binary
      run: cp target/${{ matrix.target }}/release/esp_exception_decoder esp_exception_decoder_${{ matrix.bin_suffix }}

    - name: Release
      uses: softprops/action-gh-release@v2.1.0
      with:
        files: esp_exception_decoder_${{ matrix.bin_suffix }}

  publish-exe-to-github:
    name: Publish exe tool to Github
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1

    - name: Cache
      uses: actions/cache@v4.1.2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: ${{ runner.os }}-stable

    - name: Install Linker
      run: |
        sudo apt update
        sudo apt install mingw-w64
    - name: Install Rust
      run: |
        rustup install stable
        rustup target add x86_64-pc-windows-gnu
        rustup show
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Release
      uses: softprops/action-gh-release@v2.1.0
      with:
        files: target/x86_64-pc-windows-gnu/release/esp_exception_decoder.exe

  publish-web-to-github:
    name: Publish web tool to GitHub
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1

      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Run wasm-pack
        run: wasm-pack build --target web --out-dir web/
      - name: Make an archive for web deployment
        run: tar czf esp_exception_decoder_wasm.tar.gz -C web index.html esp_exception_decoder_rs.js esp_exception_decoder_rs_bg.wasm

      - name: Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: esp_exception_decoder_wasm.tar.gz

      - name: Copy files for GitHub Pages deployment
        run: mkdir -p public; cp web/index.html web/esp_exception_decoder_rs.js web/esp_exception_decoder_rs_bg.wasm public/

      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: public
          retention-days: 1
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
